// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWrKF6N1T-tyZ41FIBV5N8D21aJqmHxQk',
    appId: '1:243899372514:web:1d003485ac3696d4c8dfbb',
    messagingSenderId: '243899372514',
    projectId: 'autonomamoviles',
    authDomain: 'autonomamoviles.firebaseapp.com',
    databaseURL: 'https://autonomamoviles-default-rtdb.firebaseio.com',
    storageBucket: 'autonomamoviles.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt0W9joQo40_PTtYAALtiLM6l7ZY5Ty9A',
    appId: '1:243899372514:android:6cb6c5521d355806c8dfbb',
    messagingSenderId: '243899372514',
    projectId: 'autonomamoviles',
  databaseURL: 'https://autonomamoviles-default-rtdb.firebaseio.com',    
  storageBucket: 'autonomamoviles.firebasestorage.app',
  );
}
